### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by Cnordbo** [TCB-Internet-Solutions/vulcan#1]
Hi there, i just pulled down the project from GitHub, and havent made any changes to it - Using the vanilla setup - im getting some missing definitions.

How to reproduce: 

1. Download project as .zip
2. Open solution in VS (im using 2015)
3. Restore packages

Expected result: 
No errors

Actual result: 
Missing definitions in several files

Heres an outtake on some of them. 

![skjermdump_020817_015909_pm](https://cloud.githubusercontent.com/assets/385693/22738209/b7db40fe-ee06-11e6-88cc-93e7180daee5.jpg)
![skjermdump_020817_015933_pm](https://cloud.githubusercontent.com/assets/385693/22738221/c6047dda-ee06-11e6-8b72-a1af3ac35c84.jpg)
![VulvanHelper](https://cloud.githubusercontent.com/assets/385693/22738230/e0202458-ee06-11e6-8eee-a79504dfcafb.jpg)

**Comment by Cnordbo** [comment]
Solution: 

For some reason, the NEST and ElasticSearch version was updated to v5.x - which resulted in these errors.

**Comment by dan-matthews** [comment]
Thanks for feedback - I did quickly test and seemed OK... as you noticed, we haven't upgraded to 5.x yet. We will do (probably next major release) but we need to find time to get it working and test first :)
