### ISSUE TITLE
New Content on Publish Event indexes content link property with work ID

### ISSUE THREAD

**Issue by peetah74** [TCB-Internet-Solutions/vulcan#13]
New Content on Publish Event indexes content link property with work ID

**Comment by bmcdavid** [comment]
@dan-matthews  I worked with @peetah74 on this. Do you have any ideas on how we can strip work version from any property of type ContentReference during serialization? As a temp fix, I had him use a content loader in a custom IVulcanHandler to load a version of the IContent that didn't use the work ID for serialization.  Would be nice to solve this for all ContentReference properties though beyond the default ContentLink on all IContent items.
