### ISSUE TITLE
Service_DeletedContent in VulcanIndexSynchronization throws exception 

### ISSUE THREAD

**Issue by oszedev** [TCB-Internet-Solutions/vulcan#15]
When using methods like _contentRepository.DeleteChildren(contentLink, force, AccessLevel.NoAccess) the index synchronization fails due to e.Content being null.
e.Content.GetTypeName() throws exception on content == null.
This should also be the case when empty the waste basket although I have not verified this yet.

Edit: Just tested with empty waste basket and it throws the same error.

**Comment by john-mckillip** [comment]
Hi. I just made a pull request that fixes this issue.

**Comment by bmcdavid** [comment]
Fixed is available in the Vulcan core NuGet package 5.0.3.
