### ISSUE TITLE
Deleting variant not updating the index.

### ISSUE THREAD

**Issue by john-mckillip** [TCB-Internet-Solutions/vulcan#2]
Hi,
I am running into an issue when a variant is deleted, it is not updating the index and causing this runtime error when doing a search after deletion: 
**contentHit doesn't implement IContent!**
It goes away if I manually re-index the content via the scheduled job. I am up to date with all Episerver and Vulcan packages. Any help is appreciated! 
Thanks,
John

**Comment by dan-matthews** [comment]
Hi John - there is an event that fires and is listened to that should remove the variant from the index. If it's not firing / being subscribed to for some reason it's an issue, I'll need to check it out when I get some time. You can check the source as well though - simply look for where we are subscribing to deletion events on IContentEvents.

**Comment by john-mckillip** [comment]
Hey Dan - cool, I'm checking it out now. Looks like line 109 in VulcanClient.cs is returning null for the result variable.  I'll dig around and see if I can find out why.
-John

**Comment by dan-matthews** [comment]
Oh wow, I see why. A really stupid bug! I'll fix it and push a new package through to the epi nuget feed asap.

**Comment by john-mckillip** [comment]
Heck yeah, thanks Dan!
