### ISSUE TITLE
Scheduled Jobs and default Vulcan client cultureinfo

### ISSUE THREAD

**Issue by bmcdavid** [TCB-Internet-Solutions/vulcan#8]
At @websolutions, we recently came across an issue with a scheduled job that used Vulcan to determine if content already exists. The issue came down to using the default handler.GetClient() which uses the current UI culture. In this case it was 'en-US', but content was index as 'en'. 

Does anyone have a recommendation on how to handle this for scheduled jobs? Trying to see if this is something we can accommodate in the core package, or at very least document it for any others who come across the issue.

**Comment by dan-matthews** [comment]
You can always call GetClients() and iterate through them to find if the content exists in any of the cultures. Might be nice to write an extension to do something similar?

**Comment by bmcdavid** [comment]
Thanks Dan, the client's site in this case only had 1 language, so we just hard coded the expected CultureInfo. I mainly just wanted to document the issue in case anyone else comes across using Vulcan in a scheduled job to determine if content already exists.
